name: Docker Build and Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build with buildx
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t hayfrp_file_node:${{ steps.sha.outputs.short_sha }} -o type=tar,dest=- . > hayfrp_file_node_${{ steps.sha.outputs.short_sha }}.tar

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hayfrp_file_node_${{ steps.sha.outputs.short_sha }}.tar
          path: hayfrp_file_node_${{ steps.sha.outputs.short_sha }}.tar