name: Docker Build and Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build with buildx
        run: |
          docker build -t hayfrp_file_node .
      
      - name: Save image as tar file
        run: |
          docker save -o hayfrp_file_node_${{ steps.sha.outputs.short_sha }}.tar hayfrp_file_node

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hayfrp_file_node_${{ steps.sha.outputs.short_sha }}.tar
          path: hayfrp_file_node_${{ steps.sha.outputs.short_sha }}.tar